version: '3'

services:
  db:
    image: postgres:16
    hostname: db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: api
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
